AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-examples-serverless-pdf
  
  SAM Template for aws-examples-serverless-pdf

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  GeneratePDFApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
  GeneratePDFFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pdf/
      Handler: pdf
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pdf
            Method: GET
            RestApiId:
              Ref: GeneratePDFApi
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GeneratePDFApi:
    Description: "API Gateway for generating PDFs"
    Value: !Sub "https://${GeneratePDFApi}.execute-api.${AWS::Region}.amazonaws.com/v1/pdf/"
  GeneratePDFFunction:
    Description: "Generate PDF function ARN"
    Value: !GetAtt GeneratePDFFunction.Arn
  GeneratePDFFunctionIamRole:
    Description: "Implicit IAM Role created for GeneratePDFFunction"
    Value: !GetAtt GeneratePDFFunctionRole.Arn
